replicaCount: 1

image:
  repository: acrtest6695.azurecr.io/flask-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

ingress:
  enabled: false

resources: {}

# Enable or disable auto-scaling for the backend
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
